### ISSUE TITLE
Any solution to customise master.cf keeping facilities of this formula

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/postfix-formula#46]
Hi,

I'm successfully using this formula, but I extend it to modify master.cf to enable/change maildrop configuration (see http://www.postfix.org/MAILDROP_README.html) with something like this:

```
postfix_master:
  file.managed:
    - name: '/etc/postfix/master.cf'
    - source: salt://mail_srv/files/master.cf
    - require:
      - pkg: postfix

include:
  - postfix.config
  - postfix

extend:
  postfix:
    service:
      - watch:
        - file: postfix_master
```

It works well, but it have a major caveat: I can't use this formula 'facilities' like the parameter `enable_submission: True` because I override master.cf with mine.
It's logical but it complexifies management of different setups (with or without submission for example) as I need to manage several master.cf sources.

I wonder if there should have any possibility to manage master.cf but with the ability to customise specific lines?
Example I want to change maildrop line, my pillar looks something like

```
master_config:
  maildrop: unix  -       n       n       -       -       pipe
      flags=ODRhu user=vmail argv=/path/to/maildrop -d ${recipient}
```

and the formula manage master.cf but change the line for maildrop.

I have no idea if this possible (in Salt, in this formula) but it could be great :)

thanks for your job.
