### ISSUE TITLE
Does this formula completely manage SASL use?

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/postfix-formula#47]
Hi,

I started using the sasl parameters for this formula, my pillar looks like

```
postfix:
  config:
    smtpd_sasl_auth_enable: yes
    smtpd_sasl_security_options: noanonymous, noplaintext
    smtpd_sasl_tls_security_options: $smtpd_sasl_security_options
    smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd

  mapping:
    smtp_sasl_password_maps:
      - mail.example.com: user1:pass1
      - mail.example.com: user2:pass2
```

It creates /etc/postfix/sasl/smtpd.conf 

```
pwcheck_method: auxprop
auxprop_plugin: sasldb
mech_list: PLAIN LOGIN CRAM-MD5 DIGEST-MD5
```

and also /etc/postfix/sasl_passwd and its postmap .db

But I got errors in mail.log like this

```
warning: SASL authentication problem: unable to open Berkeley db /etc/sasldb2: Permission denied
```

I fix it changing /etc/sasldb2 user to postfix.

I then got more authentication errors that I solved using saslpasswd2, so iit seems that /etc/sasldb2 is not managed by this formula.

Is this normal (I thought cyrus sasl config will be changed to use /etc/postfix/sasl_passwd), do I need to manage it by myself, or did I miss something?

Thanks
