### ISSUE TITLE
Don't call 'newaliases' if the 'alias_maps' postfix setting has 'regexp' as its dictionary type

### ISSUE THREAD

**Issue by petarmaric** [saltstack-formulas/postfix-formula#50]
Here's an excerpt from my Pillar:
```
postfix:
  config:
    alias_maps: regexp:/etc/aliases
    alias_database: regexp:/etc/aliases

  aliases: |
    # Forward all local *nix users mail to our admins (via greedy regexp)
    /.+/    admins@example.com
# ...
```

Running ``state.apply`` results in a rather cryptic error:
```
...
          ID: run-newaliases
    Function: cmd.wait
        Name: newaliases
      Result: False
     Comment: Command "newaliases" run
     Started: 08:29:38.848092
    Duration: 1018.418 ms
     Changes:
              ----------
              pid:
                  24312
              retcode:
                  1
              stderr:
                  postalias: fatal: unsupported dictionary type: regexp. Is the postfix-regexp package installed?
              stdout:
...
```

We shouldn't presume that everyone is using ``hash`` as their dictionary type, as 'newaliases' should not be called if the 'alias_maps' postfix setting has ``regexp`` as its dictionary type.

References:
- http://www.postfix.org/postmap.1.html see description of the ``file_type`` argument
- http://postfix.1071664.n5.nabble.com/first-timer-using-postmap-help-please-td14908.html
